language: node_js
node_js:
- 10.16.0
addons:
  ssh_known_hosts:
  - "$QA_SERVER"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_df4d0c9906af_key -iv $encrypted_df4d0c9906af_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key
before_script:
- echo -e "Host $QA_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g @angular/cli
- npm install -g bower
- npm install -g firebase-tools
script:
- cd client
- npm install
- npm run build-ci
- cd ../
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x .travis/deploy.sh && .travis/deploy.sh qa
  on:
    branch: master
notifications:
  slack:
    rooms:
    - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#code
    - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#meetr-dev
