language: node_js
node_js:
- 10.16.0

addons:
  ssh_known_hosts:
  - $QA_SERVER

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_b16825f540fe_key -iv $encrypted_b16825f540fe_iv
  -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa

before_script:
- echo -e "Host $QA_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g @angular/cli
- npm install -g bower
- npm install -g firebase-tools

script:
- cd client
- npm install
- npm run build-ci
- cd ../

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x .travis/deploy.sh && .travis/deploy.sh $QA_SERVER
  on:
    branch: master

notifications:
  slack:
    rooms:
    - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#code
    - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#meetr-dev